# Generated by Django 4.2 on 2023-05-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bid_alter_listings_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='price',
            field=models.FloatField(),
        ),
    ]
