# Generated by Django 4.2 on 2023-05-24 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listings_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
